---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Check version of hub.foobar
      ansible.builtin.debug:
        msg: "hub.foobar version: {{ lookup('hub.foobar.collection_version', 'hub.foobar') }}"
