---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Check version of bmclaughlin.test_collection
      ansible.builtin.debug:
        msg: "bmclaughlin.test_collection version: {{ lookup('bmclaughlin.test_collection.collection_version', 'bmclaughlin.test_collection') }}"
